### ISSUE TITLE
Error in UseMethod("fixef")

### ISSUE THREAD

**Issue by cooperr11** [aloy/lmeresampler#18]
Hi there,
I'm running into an error only for specific types of bootstrap methods. The below error occurs whenever I try to use the wild or residual bootstrap, but no error occurs using the parametric or case bootstrap.
> wild_boot <- bootstrap(model, .f=fixef, type="wild", hccme="hc3", aux.dist="f2", B=10)
Error in UseMethod("fixef") : 
  no applicable method for 'fixef' applied to an object of class "NULL"
The model I specified is:
model <- lmer(cbcl~ MLC*time + interview_age + (1|site_id) + (1|rel_family_id),
              data = long, na.action = na.omit)
Is it something to do with having multiple random effects?
Thanks.

**Comment by aloy** [comment]
Hi @cooper11,

Could you provide the data set so that I have a reproduible example of this issue?

--

**Comment by aloy** [comment]
@cooperr11 , Did you try to add an example via email? It didn't seem to work.

**Comment by cooperr11** [comment]
Yes via email. I'll try via github. I've uploaded as a .csv.
[long.csv](https://github.com/aloy/lmeresampler/files/7094399/long.csv)

**Comment by cooperr11** [comment]
I'm using R v 4.1.1 (64-bit) if that helps. Sorry I'm a newbie  to R :S

**Comment by aloy** [comment]
@cooperr11, I just pushed a commit where this issue should be resolved. It appears the issue was coming from the `na.action`. Let me know if you still hit the issue after you install the latest version!

```
remotes::install_github("aloy/lmeresampler")
```
