### ISSUE TITLE
Not working in the latest R: R version 4.1.2 (2021-11-01) -- "Bird Hippie"

### ISSUE THREAD

**Issue by itchyshin** [aloy/lmeresampler#21]
Could you please make this cool package work for the version above, please?

**Comment by aloy** [comment]
I will be submitting an update to CRAN today or tomorrow. I removed the dependency that was causing issues over the last year or two on CRAN, so it shouldn't be archived again.

**Comment by aloy** [comment]
The package was accepted by CRAN so it should be available soon. In the mean time, you can install it from GitHub.
