### ISSUE TITLE
Case bootstrapping_slope variance component

### ISSUE THREAD

**Issue by yasinalt** [aloy/lmeresampler#3]
I was trying to use bootstrap function in lmeresampler with type="case" for a multilevel regression problem. What I noticed that when there is only a random intercept in the model, the results for the parameter estimates between the usual lmer function and bootstrap(original) agree. However, when I add a random slope component into the model, they do not agree. I think they are always supposed to be the same? Maybe I am doing something wrong. I include the relevant code below.   

library(lme4)
vcmodA1 <- lmer(mathAge11 ~ mathAge8 + gender + class + (1 | school), data = jsp728)
summary(vcmodA1)

## you can write your own function to return stats, or use something like 'fixef'
mySumm <- function(.) {
s <- getME(., "sigma")
c(beta = getME(., "beta"), sigma = s, sig01 = unname(s * getME(., "theta")))
}

boo1 <- bootstrap(model = vcmodA1, fn = mySumm, type = "case", B = 100, resample = c(TRUE, FALSE))
require("boot")
boo1

vcmodA2 <- lmer(mathAge11 ~ mathAge8 + gender + (class | school), data = jsp728)
summary(vcmodA2)

boo2 <- bootstrap(model = vcmodA2, fn = mySumm, type = "case", B = 100, resample = c(TRUE, FALSE))
boo2

**Comment by aloy** [comment]
Thanks for letting me know. I'll take a look at this soon!

**Comment by yasinalt** [comment]
Thanks in advance!

**Comment by aloy** [comment]
When I run `mySumm(vcmodA2)` and then look at `boo2` they agree. Sorry that I never got back to you years ago!
