### ISSUE TITLE
glmer compatibility

### ISSUE THREAD

**Issue by bachlaw** [aloy/lmeresampler#4]
This is a wonderful (and unique) collection of tools. Have you adapted (or do you have any hacks / suggestions for adapting) this code for generalized linear mixed effects models (glmer), such as binomial models?

**Comment by aloy** [comment]
@bachlaw I'm hoping to tackle this extension this summer.

**Comment by aloy** [comment]
Hi @bachlaw, glmerMod objects are supported in the development version now.
