### ISSUE TITLE
The package is removed from CRAN

### ISSUE THREAD

**Issue by Generalized** [aloy/lmeresampler#5]
Dear Authors,
You made an awesome work by unifying the bootstrapping framework for both lme4 and nlme (ignored by so many users focused mostly on the lme4). But now I can see the package is removed from CRAN. Is it possible to restore it, or is it abandoned?

```
Package ‘lmeresampler’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2019-03-01 as check problems were not corrected in time. 

```

**Comment by aloy** [comment]
This slipped through the cracks. I am working to get it restored within the
next few days.

**Comment by aloy** [comment]
@Generalized, lmeresampler is back on CRAN
